branches:
  only:
    - master

init:
  - git config --global core.autocrlf true

environment:
  nodejs_version: "0.12"
  access_token:
    secure: 1WheHu+kkZmDJrayiqakzJvDUfL6OOkzc3a+sd3RM6hJcjOvIJcvrOzegNHHzbCV

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install -g hexo-cli
  - npm install

cache:
  - node_modules -> package.json
  
  # Don't actually build.
build: off

on_success:
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  - git config --global credential.helper store
  - git config --global user.email "hmemcpy@gmail.com"
  - git config --global user.name "Igal Tabachnik"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - hexo deploy