menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/hmemcpy
    Rss: /atom.xml

favicon: /favicon.ico
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: hmemcpy
duoshuo: 

# Analytics
# google-analytics:
ga:

# Copyright Infomation
startyear: 2009

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
